name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docov from repo
        run: python3 -m pip install .
        
      - name: Analyze docstring coverage of docov
        run: docov docov
        
      - name: Print docov report
        run: cat docov.txt
