name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docov locally
        run: |
          python3 -m pip install .
          docov docov
