name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docov from repo
        run: python3 -m pip install .
        
      - name: Analyze docstring coverage of docov
        run: docov docov --output .github/
      - name: Print docov report
        run: cat .github/docov.txt

      - name: Archive docstring coverage results
        uses: actions/upload-artifact@v2
        with:
          name: docov-results
          path: .github/
        
