name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  docov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install docov from repo
        run: python3 -m pip install .
        
      - name: Analyze docstring coverage of docov
        run: docov docov --output .github/workflows/.docov/
        
      - name: Print docov report
        run: cat .github/workflows/.docov/docov.txt

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: .github/workflows/.docov
        
